2018-10-20 11:10:36,682 INFO: blog startup [in C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\__init__.py:43]
2018-10-20 11:10:56,389 INFO: blog startup [in C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\__init__.py:43]
2018-10-20 11:11:05,172 INFO: blog startup [in C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\__init__.py:43]
2018-10-20 11:11:38,193 INFO: blog startup [in C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\__init__.py:43]
2018-10-20 11:36:01,137 INFO: blog startup [in C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\__init__.py:43]
2018-10-20 11:40:29,838 INFO: blog startup [in C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\__init__.py:43]
2018-10-20 11:40:38,869 ERROR: Exception on /user/max [GET] [in c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2293, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1816, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\routes.py", line 101, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\maxlv\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 134, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 869, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\loaders.py", line 125, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\templates\user.html", line 34, in template
    <hr> {% for post in posts %} {% include '_post.html' %} {% endfor %} {% endblock %}
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\environment.py", line 497, in _parse
    return Parser(self, source, name, encode_filename(filename)).parse()
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 901, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 268, in parse_block
    node.body = self.parse_statements(('name:endblock',), drop_needle=True)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 130, in parse_statement
    return getattr(self, 'parse_' + self.stream.current.value)()
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 212, in parse_if
    node.body = self.parse_statements(('name:elif', 'name:else',
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 165, in parse_statements
    result = self.subparse(end_tokens)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 883, in subparse
    rv = self.parse_statement()
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 144, in parse_statement
    self.fail_unknown_tag(token.value, token.lineno)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 97, in fail_unknown_tag
    return self._fail_ut_eof(name, self._end_token_stack, lineno)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 90, in _fail_ut_eof
    self.fail(' '.join(message), lineno)
  File "C:\Users\MaxlV\AppData\Roaming\Python\Python37\site-packages\jinja2\parser.py", line 59, in fail
    raise exc(msg, lineno, self.name, self.filename)
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'endblock'. You probably made a nesting mistake. Jinja is expecting this tag, but currently looking for 'elif' or 'else' or 'endif'. The innermost block that needs to be closed is 'if'.
2018-10-20 11:41:12,402 INFO: blog startup [in C:\Users\MaxlV\OneDrive\Documents\Job Opportunities\Perfect Sense\blog-app\app\__init__.py:43]
